### PR TITLE
Task-2 Initial commit

### PR DESCRIPTION
**Pull request by kumar-vipin**
### `Deployed demo site details`
**Site is available via S3 bucket:** 
http://my-store-app-vks.s3-website-us-east-1.amazonaws.com/

**Site is available via cloudfront:** 
https://d36w5ofpa2vi1i.cloudfront.net/

### CODE REVIEW

**Comment by yrypka** [comment]
> Site is available via S3 bucket:
http://my-store-app-vks.s3-website-us-east-1.amazonaws.com/

@kumar-vipin This link doesn't work. I got 403 Forbidden response.

**Comment by yrypka** [comment]
This is expected behavior I guess. I assume it worked before policies were changed.
Would be nice if you specified what was done and what wasn't. As I understand you decided not to do optional/additional tasks so it's 70 points, correct?

**Review by yrypka — APPROVED** [review]

**Review by kumar-vipin — COMMENTED** [review]
Looks good to me

**Comment by kumar-vipin** [comment]
checked

**Pull request merged**
